typography_spectrum: 0.28383956430479884
color:
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  brandStrength: 0.6753802865277976
  lightness: 0.9859000535216182
  saturation: 0.7035318806301802
  rhythmicContrast: 0.7679913425818086
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8842710223980248
analytics:
  google: null
  facebook: null
  twitter: null
name: michaelreynolds
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Pictures
    id: 87102b65-2dc2-4d0d-a028-884626172db2
    type: content
  - name: Pictures
    id: 5f9ed6cc-1a87-4b8c-80e2-c5cf36151bee
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: ''
description: ''
purpose: []
