typography_spectrum: 0.25798
color:
  brandColors:
    - '#383838'
    - '#cecece'
    - '#9f9f9f'
    - '#767676'
    - '#ebebeb'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.65445
analytics:
  google: null
  facebook: null
  twitter: null
name: michaelreynolds
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Leviathan and God’s Sovereignty
    id: 76aac51c-b94b-4736-91a0-8810c82ea800
    type: content
  - name: Job’s Vision of God’s Compassion and Mercy
    id: 6c287d78-7f27-4687-b8df-a6e308aade82
    type: content
  - name: Baptism for Boldness
    id: 7be14d1a-3f91-4c1f-b610-909dad14f708
    type: content
  - name: Videos
    id: 64b65732-f391-4ed7-9471-bc8fb129212b
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: An American
description: Living in Iraq
purpose: []
